---
- hosts: master
  become: true
  vars_files:
  - variables 
  tasks:
  - name: Remove config.toml file
    file:
      path: /etc/containerd/config.toml
      state: absent

  - name: Restart Docker service
    service:
      name: containerd
      state: restarted

  - name: Initializing Kubernetes cluster
    shell: kubeadm init --control-plane-endpoint=192.168.56.100 --pod-network-cidr=172.16.0.0/16

  - name: Copying required files
    shell: |
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Network Add-on
    command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

  - name: Retrieve Kubernetes join command that is used to join worker node(s)
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Print return information from the previous task
    debug:
      var: join_command

  - name: Attach kubeadm join command to a file on Ansible control node
    delegate_to: localhost
    copy:
      content: "{{ join_command.stdout_lines[0] }}"
      dest: ./join-command

#  - name: Attach kubeadm join command to a file on Ansible control node
#    local_action: 
#      module: copy
#      src: '{{ join_command.stdout_lines[0] }}' 
#      dest: ./join-command