---
- hosts: all
  become: true
  tasks:
  - name: Install the dependencies
    yum:
      name: 
        - net-tools
        - wget
        - yum-utils
        - device-mapper-persistent-data 
        - lvm2
      state: present

  - name: Upgrade all packages
    yum:
      name: "*"
      state: latest

  - name: Build hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: '{{ hostvars[item].ansible_host }} {{item}}'
      state: present
    with_items: '{{ groups["all"] }}'

  - name: Disable Selinux
    selinux:
      policy: targeted
      state: disabled

  - name: Disable Firewall
    service:
      name: firewalld
      state: stopped
      enabled: no

  - name: Add and enable official Docker Repository to CentOS 7
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0644

  - name: Install the latest Docker version on CentOS 7
    yum:
      name: docker-ce
      state: latest

  - name: Starting and Enabling Docker service
    service:
      name: docker
      state: started
      enabled: true

  - name: Create kubernetes repo file
    file:
      path: /etc/yum.repos.d/kubernetes.repo
      state: touch

  - name: Add K8s Source
    blockinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      block: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Install Kubelet on CentOS 7
    yum:
      name: kubelet
      state: latest

  - name: Install kubeadm and kubectl on CentOS 7
    yum:
      name: kubeadm
      state: latest

  - name: Disable Swap
    shell: swapoff -a

  - name: Commenting Swap entries in /etc/fstab 
    replace:
      path: /etc/fstab
      regexp: '(.*swap*)'
      replace: '#\1'

  - name: Update iptables config
    blockinfile:
      path: /etc/sysctl.d/k8s.conf
      block: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1

  - name: Apply new settings
    command: sysctl --system
