---
- hosts: all
  become: true
  vars_files:
  - variables
  tasks:
  - name: Install the dependencies
    yum:
      name: 
        - yum-utils
        - device-mapper-persistent-data 
        - lvm2
      state: present

  - name: Build hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: '{{ hostvars[item].ansible_host }} {{item}}'
      state: present
    with_items: '{{ groups["all"] }}'

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap

  - name: Disable swap
    command: swapoff -a

  - name: Disable Selinux
    selinux:
      policy: targeted
      state: disabled

  - name: Disable Firewall
    service:
      name: firewalld
      state: stopped
      enabled: no

  - name: Add official Docker Repository to CentOS 7
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0644

  - name: Install the latest Docker version on CentOS 7
    yum:
      name: containerd
      state: present
      update_cache: yes

  - name: Start & enable Docker service
    service:
      name: containerd
      state: started
      enabled: true

  - name: Add K8s Source
    blockinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      create: true
      block: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Install Kubelet on CentOS 7
    yum:
      name: kubelet
      state: latest

  - name: Starting and Enabling Kubelet
    service:
      name: kubelet
      state: started
      enabled: true

  - name: Install kubeadm and kubectl on CentOS 7
    yum:
      name: kubeadm
      state: latest

  - name: Ensure net.bridge.bridge-nf-call-ip6tables is set to 1
    sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

  - name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

  - name: Remove config.toml file
    file:
      path: /etc/containerd/config.toml
      state: absent

  - name: Restart Docker service
    service:
      name: containerd
      state: restarted

  - name: Initializing Kubernetes cluster
    when: inventory_hostname in groups['master']
    command: kubeadm init --control-plane-endpoint=192.168.56.100 --pod-network-cidr=172.16.0.0/16

  - name: Set up Kubernetes for not root user
    become: false
    when: inventory_hostname in groups['master']
    shell: |
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config
      
#  - name: Install Flannel Network Add-on
#    become: false
#    when: inventory_hostname in groups['master']
#    command: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
#
#  - name: Retrieve Kubernetes join command that is used to join worker node(s)
#    become: false
#    when: inventory_hostname in groups['master']
#    command: kubeadm token create --print-join-command
#    register: join_command_raw
#
#  - name: Set join command
#    set_fact:
#      join_command: "{{ join_command_raw.stdout_lines[0] }}"
#    when: inventory_hostname in groups['master']
#
#  - name: Join node to the cluster
#    shell: "{{ hostvars['master.example.com'].join_command }}"
#    when: inventory_hostname in groups['workers']