---
- hosts: all
  become: true
  vars_files:
  - variables
  tasks:
  - name: Install the dependencies
    yum:
      name: 
        - yum-utils
        - device-mapper-persistent-data 
        - lvm2
      state: present

  - name: Build hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: '{{ hostvars[item].ansible_host }} {{item}}'
      state: present
    with_items: '{{ groups["all"] }}'

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a

  - name: Disable Selinux
    selinux:
      policy: targeted
      state: disabled

  - name: Disable Firewall
    service:
      name: firewalld
      state: stopped
      enabled: no
