---
- hosts: all
  vars_files:
  - variables
  become: true
  tasks:
  - name: Add official Docker Repository to CentOS 7
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0644

  - name: Install the latest Docker version on CentOS 7
    yum:
      name: docker-ce
      state: latest

  - name: Start & enable Docker service
    service:
      name: docker
      state: started
      enabled: true

  - name: Add K8s Source
    blockinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      create: true
      block: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Install Kubelet on CentOS 7
    yum:
      name: kubelet
      state: latest

  - name: Starting and Enabling Kubelet
    service:
      name: kubelet
      state: started
      enabled: true

  - name: Install kubeadm and kubectl on CentOS 7
    yum:
      name: kubeadm
      state: latest

  - name: Enabling Bridge Firewall Rule I
    blockinfile:
      path: /etc/sysctl.d/k8s.conf
      create: true
      block: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1

  - name: Enabling Bridge Firewall Rule III
    shell: sysctl --system